### ISSUE TITLE
Add a “Mamota” command for users.

### ISSUE THREAD

**Issue by ImNotBee** [PHermanov/WfpChatBotConsole#44]
As an (un)authorized user, I want to call the “Mamota” command, so that the system assign a random user as a “pidor”.

AC:

GIVEN I'm (un)authorized user in the game

WHEN I text the command **/mamota**

THEN the system randomly selects a registered user in the game from the database
AND text the next message to the group: “Мамота каже що, ти **selected user** підор і він тебе їбав!”

**Comment by PHermanov** [comment]
done
